### ISSUE TITLE
t-tree组件，可选择时，在树宽度不足的情况下，选择框会被压扁

### ISSUE THREAD

**Issue by QAQCup** [Tencent/tdesign-vue-next-starter#687] opened 2024-02-23 09:53 UTC
### tdesign-vue-next-starter 版本

0.9.0

### 重现链接

https://tdesign.tencent.com/vue-next/components/tree

### 重现步骤

![1708681708318](https://github.com/Tencent/tdesign-vue-next-starter/assets/47777659/ed272bdb-8942-41c2-9bbe-3d9699a2f27b)

### 期望结果

选择框正常显示，后面的label可以超出部分隐藏

### 实际结果

选择框没有正常显示

**Comment by uyarn** [comment] 2024-02-29 01:40
duplicate of https://github.com/Tencent/tdesign-common/issues/1731
has been fixed by https://github.com/Tencent/tdesign-common/pull/1732

**Closed by uyarn** 2024-02-29 01:40 UTC
Labels: Upstream
